name: Wine Fedora CI

on:
  schedule:
    - cron:  '25 9,21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:

      - uses: actions/checkout@v4
      - name: Compilation
        run: |
          sudo dnf -y -q upgrade --refresh
          cd wine-tkg-git 
          sed -i 's/distro=""/distro="fedora"/' customization.cfg
          touch tarplz
          yes|./non-makepkg-build.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wine-tkg-build
          path: wine-tkg-git/non-makepkg-builds
