name: Wine LoL CI

on:
  schedule:
    - cron:  '25 9,21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - name: Compilation
        run: |
          sudo dpkg --add-architecture i386 && sudo apt update
          sudo apt install aptitude
          sudo aptitude remove -y '?narrow(?installed,?version(deb.sury.org))'
          cd wine-tkg-git 
          sed -i 's/distro=""/distro="debuntu"/' customization.cfg
          sed -i 's/lol920_fix="false"/lol920_fix="true"/' customization.cfg
          echo '_ci_build="true"' >> customization.cfg
          touch tarplz
          yes|./non-makepkg-build.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wine-tkg-build
          path: wine-tkg-git/non-makepkg-builds
